name: Deploy MkDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (no requirements.txt)
        run: |
          which python; python -V
          which pip;    pip -V
          # Ensure pip and python are the same interpreter
          python -m pip install --upgrade pip
          python -m pip install             mkdocs             mkdocs-material             mkdocs-awesome-pages-plugin             mkdocs-roamlinks-plugin             mkdocs-mermaid2-plugin
          # Sanity check: verify plugin import path
          python - <<'PY'
import sys, importlib
print("python exe:", sys.executable)
import mkdocs; print("mkdocs version:", mkdocs.__version__)
m = importlib.import_module("mkdocs_mermaid2_plugin")
print("mermaid2 path:", m.__file__)
PY

      - name: Build site
        run: |
          python -m mkdocs --version
          python -m mkdocs build --clean

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
